schema_version: 1

context:
  name: types-pycurl
  version: 7.45.7.20251101

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 207f13450b49ef6b94189e4a8d8eedb053c2ad49d9f631fc66c2a819b76751e9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - pip
        - python >=${{ python_min }}
    script:
      - pip check

  - package_contents:
      site_packages:
        - pycurl-stubs/__init__.pyi

about:
  summary: Typing stubs for pycurl
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
